INSERT INTO meals (item_name, category, ingredients, notes) VALUES

-- =====================
-- BREAKFAST (30)
-- =====================
('Scrambled Eggs', 'Breakfast', 'eggs, butter, salt, pepper', NULL),
('Cheese Omelette', 'Breakfast', 'eggs, cheese, butter', NULL),
('Veggie Omelette', 'Breakfast', 'eggs, onion, bell pepper, cheese', NULL),
('Avocado Toast', 'Breakfast', 'bread, avocado, olive oil, salt', NULL),
('Peanut Butter Toast', 'Breakfast', 'bread, peanut butter', NULL),
('Pancakes', 'Breakfast', 'flour, eggs, milk, butter', NULL),
('Banana Pancakes', 'Breakfast', 'banana, eggs, flour, milk', NULL),
('French Toast', 'Breakfast', 'bread, eggs, milk, cinnamon', NULL),
('Greek Yogurt Bowl', 'Breakfast', 'yogurt, honey, berries', NULL),
('Granola Yogurt', 'Breakfast', 'yogurt, granola, honey', NULL),
('Oatmeal', 'Breakfast', 'oats, milk, honey', NULL),
('Apple Cinnamon Oatmeal', 'Breakfast', 'oats, apple, cinnamon, milk', NULL),
('Smoothie Bowl', 'Breakfast', 'banana, berries, yogurt', NULL),
('Protein Smoothie', 'Breakfast', 'banana, protein powder, milk', NULL),
('Egg Muffins', 'Breakfast', 'eggs, cheese, spinach', NULL),
('Breakfast Burrito', 'Breakfast', 'eggs, tortilla, cheese, onion', NULL),
('Bagel & Cream Cheese', 'Breakfast', 'bagel, cream cheese', NULL),
('Toast & Jam', 'Breakfast', 'bread, jam, butter', NULL),
('Chia Pudding', 'Breakfast', 'chia seeds, milk, honey', NULL),
('Berry Parfait', 'Breakfast', 'yogurt, berries, granola', NULL),
('Boiled Eggs', 'Breakfast', 'eggs, salt', NULL),
('Avocado Eggs', 'Breakfast', 'eggs, avocado, olive oil', NULL),
('Cottage Cheese Bowl', 'Breakfast', 'cottage cheese, fruit', NULL),
('Breakfast Sandwich', 'Breakfast', 'eggs, bread, cheese', NULL),
('Spinach Eggs', 'Breakfast', 'eggs, spinach, olive oil', NULL),
('Egg Whites Scramble', 'Breakfast', 'egg whites, onion, spinach', NULL),
('Blueberry Muffin', 'Breakfast', 'flour, blueberries, eggs', NULL),
('Chocolate Oatmeal', 'Breakfast', 'oats, cocoa, milk', NULL),
('Honey Toast', 'Breakfast', 'bread, honey, butter', NULL),
('Fruit Salad', 'Breakfast', 'apple, banana, berries', NULL),

-- =====================
-- LUNCH (30)
-- =====================
('Chicken Salad', 'Lunch', 'chicken, lettuce, olive oil', NULL),
('Grilled Cheese', 'Lunch', 'bread, cheese, butter', NULL),
('Turkey Sandwich', 'Lunch', 'bread, turkey, cheese', NULL),
('Veggie Wrap', 'Lunch', 'tortilla, lettuce, tomato, hummus', NULL),
('Pasta Salad', 'Lunch', 'pasta, olive oil, tomato, cheese', NULL),
('Quinoa Bowl', 'Lunch', 'quinoa, chickpeas, olive oil', NULL),
('Rice & Beans', 'Lunch', 'rice, beans, onion, garlic', NULL),
('Chicken Rice Bowl', 'Lunch', 'chicken, rice, garlic', NULL),
('Tuna Salad', 'Lunch', 'tuna, mayo, onion', NULL),
('Egg Salad', 'Lunch', 'eggs, mayo, mustard', NULL),
('Greek Salad', 'Lunch', 'cucumber, tomato, feta, olive oil', NULL),
('Lentil Soup', 'Lunch', 'lentils, onion, garlic, carrot', NULL),
('Chicken Wrap', 'Lunch', 'chicken, tortilla, lettuce', NULL),
('Veggie Stir Fry', 'Lunch', 'broccoli, onion, garlic, soy sauce', NULL),
('Fried Rice', 'Lunch', 'rice, eggs, onion, soy sauce', NULL),
('Pesto Pasta', 'Lunch', 'pasta, basil, olive oil, garlic', NULL),
('Chickpea Salad', 'Lunch', 'chickpeas, tomato, onion', NULL),
('Tomato Soup', 'Lunch', 'tomato, garlic, onion', NULL),
('Grilled Veggies', 'Lunch', 'zucchini, bell pepper, olive oil', NULL),
('Hummus Bowl', 'Lunch', 'hummus, pita, cucumber', NULL),
('Avocado Rice', 'Lunch', 'rice, avocado, olive oil', NULL),
('Chicken Quesadilla', 'Lunch', 'chicken, tortilla, cheese', NULL),
('Bean Burrito', 'Lunch', 'beans, tortilla, cheese', NULL),
('Spinach Pasta', 'Lunch', 'pasta, spinach, garlic', NULL),
('Curry Lentils', 'Lunch', 'lentils, onion, spices', NULL),
('Salmon Rice', 'Lunch', 'salmon, rice, olive oil', NULL),
('Chicken Soup', 'Lunch', 'chicken, carrot, onion', NULL),
('Veggie Burger', 'Lunch', 'veggie patty, bun, lettuce', NULL),
('Mac & Cheese', 'Lunch', 'pasta, cheese, milk', NULL),
('Caprese Sandwich', 'Lunch', 'bread, tomato, mozzarella', NULL),

-- =====================
-- DINNER (30)
-- =====================
('Chicken Stir Fry', 'Dinner', 'chicken, onion, garlic, soy sauce', NULL),
('Spaghetti Marinara', 'Dinner', 'pasta, tomato, garlic, olive oil', NULL),
('Beef Tacos', 'Dinner', 'beef, tortilla, onion, cheese', NULL),
('Veggie Curry', 'Dinner', 'potato, onion, garlic, spices', NULL),
('Grilled Salmon', 'Dinner', 'salmon, olive oil, lemon', NULL),
('Chicken Alfredo', 'Dinner', 'chicken, pasta, cream, garlic', NULL),
('Fried Rice', 'Dinner', 'rice, eggs, onion, soy sauce', NULL),
('Stuffed Peppers', 'Dinner', 'bell pepper, rice, cheese', NULL),
('Chicken Parmesan', 'Dinner', 'chicken, cheese, tomato', NULL),
('Veggie Pasta', 'Dinner', 'pasta, zucchini, garlic', NULL),
('Beef Stir Fry', 'Dinner', 'beef, onion, soy sauce', NULL),
('Chickpea Curry', 'Dinner', 'chickpeas, onion, garlic', NULL),
('Baked Chicken', 'Dinner', 'chicken, olive oil, spices', NULL),
('Lasagna', 'Dinner', 'pasta, cheese, tomato', NULL),
('Shrimp Rice', 'Dinner', 'shrimp, rice, garlic', NULL),
('Veggie Tacos', 'Dinner', 'beans, tortilla, onion', NULL),
('Chicken Fajitas', 'Dinner', 'chicken, bell pepper, onion', NULL),
('Pesto Chicken', 'Dinner', 'chicken, basil, olive oil', NULL),
('Eggplant Parmesan', 'Dinner', 'eggplant, cheese, tomato', NULL),
('Tofu Stir Fry', 'Dinner', 'tofu, broccoli, soy sauce', NULL),
('Coconut Curry', 'Dinner', 'coconut milk, potato, onion', NULL),
('Meatballs', 'Dinner', 'beef, breadcrumbs, garlic', NULL),
('Chicken Soup', 'Dinner', 'chicken, carrot, onion', NULL),
('Burrito Bowl', 'Dinner', 'rice, beans, chicken', NULL),
('Veggie Chili', 'Dinner', 'beans, tomato, onion', NULL),
('Salmon Pasta', 'Dinner', 'salmon, pasta, garlic', NULL),
('Roasted Veggies', 'Dinner', 'potato, carrot, olive oil', NULL),
('Chicken Tikka', 'Dinner', 'chicken, yogurt, spices', NULL),
('Rice Pilaf', 'Dinner', 'rice, onion, butter', NULL),
('Stuffed Zucchini', 'Dinner', 'zucchini, rice, cheese', NULL),

-- =====================
-- SNACKS (30)
-- =====================
('Apple & Peanut Butter', 'Snack', 'apple, peanut butter', NULL),
('Banana', 'Snack', 'banana', NULL),
('Trail Mix', 'Snack', 'nuts, raisins, chocolate', NULL),
('Yogurt Cup', 'Snack', 'yogurt', NULL),
('Cheese & Crackers', 'Snack', 'cheese, crackers', NULL),
('Granola Bar', 'Snack', 'oats, honey', NULL),
('Hummus & Carrots', 'Snack', 'hummus, carrots', NULL),
('Popcorn', 'Snack', 'corn kernels, salt', NULL),
('Protein Bar', 'Snack', 'protein bar', NULL),
('Fruit Cup', 'Snack', 'fruit', NULL),
('Rice Cakes', 'Snack', 'rice cakes', NULL),
('Dark Chocolate', 'Snack', 'chocolate', NULL),
('Boiled Egg', 'Snack', 'egg', NULL),
('Smoothie', 'Snack', 'banana, milk', NULL),
('Peanut Handful', 'Snack', 'peanuts', NULL),
('Crackers', 'Snack', 'crackers', NULL),
('Cheese Stick', 'Snack', 'cheese', NULL),
('Toast Bites', 'Snack', 'bread, butter', NULL),
('Cucumber Slices', 'Snack', 'cucumber, salt', NULL),
('Apple Slices', 'Snack', 'apple', NULL),
('Yogurt Parfait', 'Snack', 'yogurt, granola', NULL),
('Energy Balls', 'Snack', 'oats, peanut butter, honey', NULL),
('Pretzels', 'Snack', 'pretzels', NULL),
('Milk Glass', 'Snack', 'milk', NULL),
('Chips', 'Snack', 'potatoes, oil', NULL),
('Salsa & Chips', 'Snack', 'tortilla chips, tomato', NULL),
('Roasted Nuts', 'Snack', 'nuts, salt', NULL),
('Frozen Grapes', 'Snack', 'grapes', NULL),
('Fruit Smoothie', 'Snack', 'berries, banana', NULL),
('Peanut Butter Crackers', 'Snack', 'peanut butter, crackers', NULL);
